### ISSUE TITLE
LibreOfficeLangPack download recipe failed

### ISSUE THREAD

**Issue by Nerthil** [autopkg/sebtomasi-recipes#5]
The recipe com.github.sebtomasi.download.LibreOfficeLangPack (Langpack dmg) overwrite the downloaded dmg (LibreOffice dmg) from the parent recipe (io.github.hjuutilainen.download.LibreOffice). Because of the overwrite the package process will fail because there is no LibreOffice.app in the language pack dmg.

```
Error in de.fau.rrze.jss.LibreOffice: Processor: Copier: Error: Error processing path '/private/tmp/dmg.MUM6ak/LibreOffice.app' with glob. 
```

The reasons is, that hjuutilainen changed the URLDownloader process to rename the downloaded dmg to "LibreOffice.dmg" and your recipe download the language pack with the same name. 

A workaround could be to add in your URLDownload process the key "filename" and rename your download to "%NAME%_langpack_%LANGUAGE_CODE%.dmg".

```XML
....
     <key>filename</key>
     <string>%NAME%_langpack_%LANGUAGE_CODE%.dmg</string>
....
```

**Comment by little2112** [comment]
I confirm, I have the same trouble with this recipe and the other one com.github.sebtomasi.pkg.LibreOfficeLangPack as well!
Is it possible to fix this error with glob?
Thank you!

**Comment by little2112** [comment]
The above noted solution works just fine! I've added those two exact lines to  com.github.sebtomasi.download.LibreOfficeLangPack recipe to the URLDownloader process so the whole process looks like this:
```
<dict>
			<key>Processor</key>
			<string>URLDownloader</string>
			<key>Arguments</key>
			<dict>
				<key>url</key>
				<string>%parsed_string%</string>
				<key>filename</key>
                <string>%NAME%_langpack_%LANGUAGE_CODE%.dmg</string>
			</dict>
		</dict>
```
All files are being created just as expected without any errors.
Thank you!

**Comment by sebtomasi** [comment]
I've reviewed the download recipe com.github.sebtomasi.download.LibreOfficeLangPack, at the end you get 2 downloaded files, the app and the langpack. The processor com.github.sebtomasi.SharedProcessors/RenameVar rename the %pathname% coming from io.github.hjuutilainen.download.LibreOffice, then we modify the original download URL with this processor com.github.sebtomasi.SharedProcessors/TextSubstituer, the exit will be downloaded. you normaly don't need to have a filename variable in URLDownloader

**Comment by grahampugh** [comment]
I also have this problem. 

```
The following recipes failed:
    LibreOfficeLangPack.pkg
        Error in local.pkg.LibreOfficeLangPack: Processor: Copier: Error: Error processing path '/private/tmp/dmg.QRUL5w/LibreOffice.app' with glob. 
```

I normally run from a self-scripted JSS recipe, but I created a direct override for your PKG recipe today, and it still fails.

**Comment by sebtomasi** [comment]
I've corrected the download recipe with the modification you asked me @little2112. thanks for your help guys.
