### ISSUE TITLE
amsysuk-recipes don't seem to exist anymore.

### ISSUE THREAD

**Issue by portalpie** [autopkg/sebtomasi-recipes#6]
Hello,

This recipe refers to a recipe that seems to be gone now.

Thanks
Morgs

**Comment by sebtomasi** [comment]
Hi @portalpie,

Apparently the amsysuk-recipes repo became https://github.com/autopkg/moofit-recipes, so I'm gonna replace the references for the Unity3D recipe.

I'll let you know asap.

Thanks for your feedback

Seb

**Comment by sebtomasi** [comment]
Hi Morgan,

The recipe identifier is still com.github.amsysuk-recipes.pkg.Unity3D even though is within moofit-recipes repo.

`autopkg info Unity3D.pkg
Description:         Creates an installer package from the parent download recipe
                         com.github.hansen-m.download.Unity3D
                         
Identifier:          com.github.amsysuk-recipes.pkg.Unity3D
Munki import recipe: False
Has check phase:     True
Builds package:      False
Recipe file path:    /Users/sebastientomasi/Library/AutoPkg/RecipeRepos/com.github.autopkg.moofit-recipes/Unity 3D/Unity3D.pkg.recipe
Parent recipe(s):    /Users/sebastientomasi/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes/Unity3D/Unity3D.download.recipe
Input values: 
 
    NAME = Unity;`

I've tried by removing the moofit-recipes repo and re add, it works. Add or Update the moofit-recipes repo.
`autopkg repo-delete moofit-recipes
autopkg repo-add moofit-recipes`

I hope this help.

Seb
